version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lmcyber/inference_back:0.1


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lmcyber/front:0.1
    ports:
      - 127.0.0.1:80:80
    depends_on:
      backend:
        condition: service_started

