version: "3.7"

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
  nginx:
    container_name: "nginx"
    build: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - api
      - web
