version: "3.7"

services:
  docker-fastapi:
    container_name: "docker-fastapi"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: lmcyber/stud_camp:0.1

    ports:
      - 8080:8080

  nginx:
    container_name: "proxy-app"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - docker-fastapi
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:3000


